services:
  web:
    build: .
    container_name: php-app
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
